Fix running Sam locally
broadinstitute/sam pull request #1047
Opened 2023-04-07 01:17 UTC by tlangs

Thanks to @em-may For help with the k8s secrets!

What:

Fix the local configuration so that Sam can be run on a dev machine outside of Docker!

Why:

Its really useful for debugging.

How:

Running Sam locally now pulls its service accounts secrets from Kubernetes instead of from Vault. This is because Sam's service account keys are rotated by Yale, and the keys in Vault are no longer updated. 

Also needed to get the proxy running locally. Now, we can even make requests to a Sam instance running locally! The proxy still relies on `firecloud-develop`.

---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've filled out the [Security Risk Assessment](https://sdarq.dsp-appsec.broadinstitute.org/jira-ticket-risk-assesment) (requires Broad Internal network access) and attached the result to the JIRA ticket

2023-04-10 15:05 UTC, Ghost-in-a-Jar commented on env/local.env
>  export AZURE_ENABLED="false"
Can you leave a comment here explaining why you commented the service accs

2023-04-10 15:05 UTC, Ghost-in-a-Jar approved these changes

2023-04-10 17:00 UTC, gpolumbo-broad requested changes

2023-04-10 17:00 UTC, gpolumbo-broad commented on render_config.sh
For the `kubectl` commands to work, we the user will surely need to do some setup/config of `kubectl` to be able to talk to the k8s cluster on google.  Please make sure the README is updated with instructions to set this up so that this script will run correctly.

2023-04-12 20:51 UTC, tlangs commented
jenkins retest

2023-04-19 16:10 UTC, tlangs commented
jenkins retest

2023-04-19 16:31 UTC, Ghost-in-a-Jar approved these changes

2023-04-19 17:18 UTC, gpolumbo-broad approved these changes

2023-04-19 17:50 UTC, merged