ID-586 Sam signs GS URLs
broadinstitute/sam pull request #1065
Opened 2023-04-27 16:12 UTC by tlangs

Ticket: https://broadworkbench.atlassian.net/browse/ID-586

What:

Sam can now return signed URLs for GS Objects! 

Why:

Martha is getting retired, and Sam already handles service account keys. It makes sense for Sam to do this, and to not pass keys over the network to other systems.

How:

The first step was to modify [workbench-libs](https://github.com/broadinstitute/workbench-libs/pull/1336) to create signed URLs for gs blobs. Then, I wired that into Sam and wrote tests.

---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've filled out the [Security Risk Assessment](https://sdarq.dsp-appsec.broadinstitute.org/jira-ticket-risk-assesment) (requires Broad Internal network access) and attached the result to the JIRA ticket

2023-04-27 17:11 UTC, Ghost-in-a-Jar approved these changes
might be worth testing out the case where the user doesnt have perms on the gs object, and potentially handling that error

2023-04-27 17:55 UTC, tlangs commented
@Ghost-in-a-Jar I'm going to deploy to a BEE and see how it fails and then implement that

2023-05-01 14:18 UTC, tlangs commented
jenkins retest

2023-05-01 17:05 UTC, tlangs commented
jenkins retest

2023-05-01 17:09 UTC, tlangs commented
@Ghost-in-a-Jar turns out google will sign any url, no matter if the object exists or not. I don't think its Sam's job to check for the existence of the object. Its only job is to use the Pet Service Account to sign the URL given.

2023-05-01 17:39 UTC, tlangs commented
jenkins retest

2023-05-01 19:39 UTC, tlangs commented
jenkins retest

2023-05-02 12:51 UTC, tlangs commented
jenkins retest

2023-05-02 13:55 UTC, tlangs commented
jenkins retest

2023-05-02 15:23 UTC, Ghost-in-a-Jar approved these changes

2023-05-02 19:02 UTC, gpolumbo-broad requested changes

2023-05-02 19:02 UTC, gpolumbo-broad commented on README.md
> +Navigate to [Sam's (Proxy's) Swagger page](https://local.broadinstitute.org:50443/#/)
If we make this change, we also need to add the step here or point to the step that instructs the user on how to modify their `/etc/hosts` file

2023-05-02 19:02 UTC, gpolumbo-broad commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleExtensions.scala
> +    googleGroupSyncPubSubDAO.publishMessages(googleServicesConfig.groupSyncPubSubConfig.topic, Seq(MessageRequest(id.toJson.compactPrint)))
Just wondering why this change is in here?  Was this one of the things screwing up tests?  Or maybe something we had to change as a result of a `workbench-libs` version upgrade?  Is this something we should be doing everywhere that we publish messages to a pub-sub queue?

2023-05-02 19:02 UTC, gpolumbo-broad commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleExtensions.scala
> +      petServiceAccount <- createUserPetServiceAccount(samUser, project, samRequestContext)
😠 I am not a fan of `createUserPetServiceAccount` both in name and implementation…but that's well out of scope for this ticket.  Just calling it out as naughty and good refactoring fodder.

2023-05-02 19:02 UTC, gpolumbo-broad commented on src/main/resources/swagger/api-docs.yaml
> +      summary: gets a signed URL for the given blob, signed by the Pet Service account of the calling user
What are credential scopes for the signed URL?  https://cloud.google.com/storage/docs/authentication/signatures#credential-scope

The above link includes an earliest available date, but I know you can also put expiration dates on the signed URL.  Not sure what other limitations can be put on a signed URL and what other defaults might be applied to the signed url.  Since we are not allowing users to specify these parameters on their own, we should do our best to describe the limitations and restrictions or whatever on the signed url.

2023-05-02 19:02 UTC, gpolumbo-broad commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleExtensions.scala
> +      url <- googleStorageService.getSignedBlobUrl(bucket, name, serviceAccountCredentials).compile.lastOrError
Note in this documentation that using this method, the signed url is good for a maximum of 12 hours.  https://cloud.google.com/storage/docs/access-control/signed-urls#signing-iam

Is that going to be a problem?  If Cromwell calls out to Sam in the middle of a run to generate the signed URL, we might be fine, if a job might be running for days or weeks, if we only pass in the signed url (and not the localized file) we might have problems.  I don't really know how cromwell does its thing with regard to this stuff though.  So maybe 12 hours is fine, just want to make sure.  We should also note the 12 hour maximum life span in the Swagger documentation.

2023-05-02 19:02 UTC, gpolumbo-broad commented on src/test/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleExtensionRoutesV1Spec.scala
> +    val (_, samRoutes, projectName) = setupSignedUrlTest()
In the spirit of test engoodening, I would love to simplify the setup here.  For example, I would consider mocking `googleExtensions.getSignedUrl` directly to return either a valid response or an exception or `Failure` or whatever corresponding to whatever that method does when it fails.  We don't need to test the functionality of `googleExtensions.getSignedUrl` in the route spec, we just need to test that the routing works properly, returns 200, 404, 4XX, 5XX, whatever.  Then we test `googleExtensions.getSignedUrl` in the `GoogleExtensionsSpec`.  

Since `setupSignedUrlTest` is also being added in this test, I would like to ask you to try writing these tests and just mocking out `googleExtensions.getSignedUrl`.  If we can avoid introducing the big complicated setup, I'd prefer to do that.  If it doesn't work, I'd be interested to see what is messing us up (in the spirit of keeping track of the design/implementation subtleties that are forcing us to write more complicated tests than we want)

2023-05-02 19:02 UTC, gpolumbo-broad commented on src/test/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleExtensionSpec.scala
🤮 OMG - this file is SMELLY!  Just the number of lines it and the `GoogleExtensions` constructor repeated 8 billion times with the gigantic parameter list… eww eww eww eww

I think it would be a good idea to do something to get us started with "better" testing here.  Maybe create a new `GoogleExtensionSpecNewAndImproved` or something that does all of this stuff… better.  All it needs to have in it for now is the 1 new test you are adding, just something to get us started on writing all these tests better so that they're more clear, more specific, and overall easier to understand and maintain.

For example, we could make something like a `MockGoogleExtensionBuilder` (see `MockDirectoryDaoBuilder`) so we don't have all those repetitive `null`s and yuck.  The idea would be, yeah, it's a little extra work for this PR, but _somebody_ has to be first.  Then the next person who has to do something in _this_ file, we point them to do it in the new file.  Every time we do that, it will get a little easier and a little better. Bit by bit, I think that's the way we'll need to tackle this.

2023-05-02 19:02 UTC, gpolumbo-broad commented on src/test/scala/org/broadinstitute/dsde/workbench/sam/mock/RealKeyMockGoogleIamDAO.scala
I'm wondering if we need this class?  From my quick search through the code, it looks to me like you're just mocking out calls to create a key anyway.  In general, if we can avoid mocking out implementation like this, the better.  If there are ways the code is designed that is making the mocking of this challenging, we should consider changing those designs.

2023-05-02 19:04 UTC, gpolumbo-broad commented on src/test/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleExtensionSpec.scala
Just to be clear, it's not YOUR code I'm complaining about.  It's the overall mess that this test suite has become over the years.  :)

2023-05-02 19:05 UTC, tlangs commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleExtensions.scala
> +    googleGroupSyncPubSubDAO.publishMessages(googleServicesConfig.groupSyncPubSubConfig.topic, Seq(MessageRequest(id.toJson.compactPrint)))
This is a result of the upgrade to workbench-libs

2023-05-02 19:06 UTC, tlangs commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleExtensions.scala
> +      url <- googleStorageService.getSignedBlobUrl(bucket, name, serviceAccountCredentials).compile.lastOrError
This isn't being used by Cromwell. It's being used by the UI to generate download links. Also, these links are good for 1 hour, not 12, which is what Martha was doing.

2023-05-02 19:08 UTC, tlangs commented on README.md
> +Navigate to [Sam's (Proxy's) Swagger page](https://local.broadinstitute.org:50443/#/)
That's already covered in the `firecloud-develop setup` portion of the README

2023-05-02 19:14 UTC, tlangs commented on src/main/resources/swagger/api-docs.yaml
> +      summary: gets a signed URL for the given blob, signed by the Pet Service account of the calling user
The scopes are the same as those of the credentials passed to Sam from the UI. Its not doing anything different from Martha here.

2023-05-02 19:18 UTC, tlangs commented on src/test/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleExtensionRoutesV1Spec.scala
> +    val (_, samRoutes, projectName) = setupSignedUrlTest()
I'm hesitant to pour effort into improving these tests. The long-ish term for Sam is to pull this functionality into a separate service, and we're trying to get DrsHub done asap so we can hand it off. I'm not sure its worth the delay to rewrite the tests.

2023-05-02 19:19 UTC, tlangs commented on src/test/scala/org/broadinstitute/dsde/workbench/sam/mock/RealKeyMockGoogleIamDAO.scala
We need this because workbench-libs requires a real-looking key even in its mocks.

2023-05-02 19:38 UTC, tlangs commented on src/test/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleExtensionSpec.scala
As above, I'm really hesitant to pour a lot of effort into refactoring these tests, since this functionality will be ripped out of Sam and put into a new service. I'd much rather direct effort at getting DRSHub off our hands so that we can get to actually yanking this functionality out of Sam sooner.

2023-05-04 14:12 UTC, tlangs commented
jenkins retest

2023-05-04 14:51 UTC, gpolumbo-broad commented
@tlangs:

> google will sign any url

I know this is documented in the google stuff, but I also think we should document our Swagger endpoints much better.  I think noting this and any other "settings" or "scopes" on the signed url endpoint is useful so that users know what to expect from our endpoint without also needing to go read through all the google documentation.  Furthermore, it means that when someone asks us a question about how this stuff behaves, we should be able to easily find the answer and not need to go read through all of our code and google documentation to take a stab at it.  If it's in the Swagger docs, they shouldn't even need to ask us in the first place.  If it's expressed via a unit test, we know, "ah, we pass through any url, even if it doesn't exist to google and have them sign it.  That was our intended behavior."

2023-05-04 15:01 UTC, gpolumbo-broad approved these changes

2023-05-04 15:12 UTC, tlangs commented
@gpolumbo-broad I added some API documentation.

2023-05-04 18:59 UTC, tlangs commented
jenkins retest

2023-05-04 20:03 UTC, tlangs commented
jenkins retest

2023-05-04 23:16 UTC, merged