ID-815 New terms of service tracking table.
broadinstitute/sam pull request #1200
Opened 2023-10-04 14:39 UTC by Ghost-in-a-Jar

Ticket: [ID-815](https://broadworkbench.atlassian.net/browse/ID-815)

What:

This pr adds a new terms of service acceptance/rejection tracking table for users. It is an append only table that tracks userid, tos version, action (accept/reject), createdat.

Why:

For auditing purposes we need to be able to look back on when users accepted or rejected different versions of the tos.

How:

I added a new append-only table and moved tos information from the SamUser class to a new one. Included in the migration is a query that grabs all of the current tos acceptance data and puts it in the new table.

---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've filled out the [Security Risk Assessment](https://sdarq.dsp-appsec.broadinstitute.org/jira-ticket-risk-assesment) (requires Broad Internal network access) and attached the result to the JIRA ticket

2023-10-04 14:41 UTC, Ghost-in-a-Jar commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/dataAccess/DirectoryDAO.scala
> +  def getUserTos(userId: WorkbenchUserId, tosVersion: String, samRequestContext: SamRequestContext): IO[Option[SamUserTos]]
This fn is for the tos database lookup for a given user and tos version.

2023-10-04 14:44 UTC, Ghost-in-a-Jar commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/db/tables/TosTable.scala
> +  val REJECT = "REJECT"
Maybe theres a better way/place to put this? Id love to have an enum but that can be a pain in scala.

2023-10-04 20:01 UTC, tlangs requested changes
This is awesome, and quite the hefty PR! Great job maintaining backwards compatibility. We'll want to thoroughly test this on Dev before pushing it out to prod.

2023-10-04 20:01 UTC, tlangs commented on src/main/resources/org/broadinstitute/dsde/sam/liquibase/changesets/20230929_add_tos_audit_table.xml
> +      <column name="accepted_tos_version"/>
😍

2023-10-04 20:01 UTC, tlangs commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/dataAccess/DirectoryDAO.scala
> +  def getUserTos(userId: WorkbenchUserId, tosVersion: String, samRequestContext: SamRequestContext): IO[Option[SamUserTos]]
Why do we need to query for a given user _and_ version?

2023-10-04 20:01 UTC, tlangs commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/dataAccess/PostgresDirectoryDAO.scala
> +        samsql"""select ${tosTable.resultAll}
We should `LIMIT 1` in this query if we're just gonna get the first anyways.

2023-10-04 20:01 UTC, tlangs commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/db/tables/TosTable.scala
> +  val REJECT = "REJECT"
This is probably fine, given scala's lack of enum types.

2023-10-04 20:36 UTC, Ghost-in-a-Jar commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/dataAccess/DirectoryDAO.scala
> +  def getUserTos(userId: WorkbenchUserId, tosVersion: String, samRequestContext: SamRequestContext): IO[Option[SamUserTos]]
I figured in case we need to roll back a tos version, also i think it cant hurt to be specific here

2023-10-10 15:45 UTC, tlangs commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/dataAccess/DirectoryDAO.scala
> +  def getUserTos(userId: WorkbenchUserId, tosVersion: String, samRequestContext: SamRequestContext): IO[Option[SamUserTos]]
I agree the method is probably useful, but I don't know if this is the right behavior for the current APIs. A `getUserLatestTos` would probably fit better.

If a user hasn't accepted then current ToS, what happens when `getUserTos` is called as a part of the `termsOfServiceDetails` API endpoint? We would want to return the `SamUserTos` details including that they've accepted the previous version, not an `Empty` response.

2023-10-10 15:56 UTC, Shakespeared approved these changes

2023-10-10 18:07 UTC, tlangs approved these changes

2023-10-11 14:12 UTC, merged