Add to pact readme.
broadinstitute/sam pull request #1233
Opened 2023-10-30 14:33 UTC by Ghost-in-a-Jar

Just adding a bit to the readme for pact

---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've filled out the [Security Risk Assessment](https://sdarq.dsp-appsec.broadinstitute.org/jira-ticket-risk-assesment) (requires Broad Internal network access) and attached the result to the JIRA ticket

2023-10-30 14:51 UTC, gpolumbo-broad requested changes
Would you please add link in the main README that for Pact/Contract testing instructions, users should read _this_ README

2023-10-30 18:48 UTC, gpolumbo-broad approved these changes

2023-10-31 18:10 UTC, sjkobori approved these changes

2023-10-31 18:10 UTC, Shakespeared approved these changes

2023-10-31 19:02 UTC, merged