[TOAZ-355] [TOAZ-356] Use Managed Identity auth when running Azure Control Plane, support for Service Catalog deployed Azure Managed Apps
broadinstitute/sam pull request #1404
Opened 2024-04-18 19:30 UTC by aaronegrant

- Refactor SAM ARM authorization code to support using a Managed Identity app id instead of Service Principal clientid/clientsecret

- Service Catalog deployed app support:
Sam maintains its own list of Terra managed app plans https://github.com/broadinstitute/sam/blob/develop/src/main/resources/sam.conf#L192 and validates a billing profile managed app against this list during billing profile creation. 
Service catalog managed apps do not have a plan defined so we will need change the validation in Sam to accept this.

2024-05-08 18:04 UTC, dvoet commented on src/main/resources/sam.conf
> +  azureControlPlaneEnabled = ${?AZURE_CONTROL_PLANE_ENABLED}
This controls specifically whether to use the service catalog or partner center managed resource groups. The name of this config setting should reflect that.

2024-05-08 18:09 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/azure/CrlService.scala
> +  def getKindServiceCatalog: String = config.kindServiceCatalog
it seems weird to expose these config settings through `CrlService` when they are used in `AzureService`.  `AzureService` probably should be passed `AzureServicesConfig` directly

2024-05-08 18:25 UTC, rtitle commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/azure/AzureService.scala
> +  private def validateServiceCatalogManagedResourceGroup(
There is not much difference between `validateServiceCatalogManagedResourceGroup` and `validateManagedResourceGroup` -- would it make sense to consolidate them?

Looks like the only difference is the service catalog app doesn't have a plan. We could potentially have a single method that looks at `managedApp.kind()` to determine whether it needs to validate the plan.

2024-05-08 18:31 UTC, rtitle commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/azure/CrlService.scala
> +      .clientId(config.managedAppWorkloadClientId)
Just confirming, if `config.managedAppWorkloadClientId` is null (which I think it would be in the Broad environment) -- will this safely be ignored (e.g. not throw an exception)?

2024-05-08 18:35 UTC, rtitle reviewed
Left a couple comments above, but overall the approach makes sense to me.

2024-05-08 18:44 UTC, aaronegrant commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/azure/CrlService.scala
> +      .clientId(config.managedAppWorkloadClientId)
Correct, there will be a message in the log file about unable to auth using Managed Identity and then fall through to the Service Principal credentials

2024-05-15 18:10 UTC, dvoet commented on src/test/scala/org/broadinstitute/dsde/workbench/sam/azure/MockCrlService.scala
> -
why was this removed? I think this is the source of your unit test errors

2024-05-16 13:49 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/azure/AzureService.scala
> +        plan <- validatePlan(managedApp, config.managedAppPlans)
I think this change is causing test failures. In unit tests, `crlService` is mocked and returns results expected by tests but inconsistent with config

2024-05-16 13:50 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/config/AppConfig.scala
> +              config.getBoolean("azureControlPlaneEnabled"),
the name `azureControlPlaneEnabled` is no longer correct

2024-05-16 13:51 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/config/AzureServicesConfig.scala
> +}
why do we have these new config readers when they already exist in AppConfig.scala?

2024-05-16 18:39 UTC, dvoet requested changes, later dismissed

2024-05-16 18:39 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/Boot.scala
> +      new AzureService(config.azureServicesConfig.get, new CrlService(azureConfig, config.janitorConfig), directoryDAO, azureManagedResourceGroupDAO)
```suggestion
      new AzureService(azureConfig, new CrlService(azureConfig, config.janitorConfig), directoryDAO, azureManagedResourceGroupDAO)
```

2024-05-16 18:39 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/azure/AzureService.scala
> +        if (false) {
probably don't mean `if (false)`

2024-05-16 18:39 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/azure/AzureService.scala
> +          if (managedApp.kind() == config.kindServiceCatalog && validateUser) {
```managedApp.kind() == config.kindServiceCatalog```
if we are here, isn't is already a service catalog?

2024-05-16 18:39 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/azure/AzureService.scala
> +              ManagedAppPlan("", "", config.authorizedUserKey),
perhaps refactor `validateAuthorizedAppUser` to take `authorizedUserKey` so we don't have to construct a dummy `ManagedAppPlan` with empty values

2024-05-16 19:16 UTC, aaronegrant commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/azure/AzureService.scala
> +          if (managedApp.kind() == config.kindServiceCatalog && validateUser) {
Not necessarily, Marketplace apps will come back here as well without this check

2024-05-21 15:34 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/azure/AzureService.scala
> +        if (Option(config).isDefined && config.azureServiceCatalogAppsEnabled) {
why would `config` be null? We should not be passing around nulls. If it truly is nullable, it should be an `Option`

2024-05-23 16:29 UTC, aaronegrant commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/azure/AzureService.scala
> +        if (Option(config).isDefined && config.azureServiceCatalogAppsEnabled) {
Switched AzureServicesConfig to Option in AzureServices. Made the check for the ServiceCatalogApps enabled flag a case statement to handle the 3 possible states of AzureServicesConfig

2024-05-24 17:59 UTC, dvoet approved these changes

2024-05-28 14:24 UTC, Shakespeared requested changes
Not super familiar with this azure functionality but changes seem reasonable to me, requested minor naming changes for clarity

2024-05-28 14:24 UTC, Shakespeared commented on src/main/resources/sam.conf
> +  kindServiceCatalog = "ServiceCatalog";
nit: the naming of `kindServiceCatalog` and `managedApp.kind` is a bit opaque to me. I understand from context but to me it's hard to interpret. Maybe something like `serviceCatalogAppType` and `managedApp.type` would be a little clearer?

2024-05-28 15:48 UTC, aaronegrant commented on src/main/resources/sam.conf
> +  kindServiceCatalog = "ServiceCatalog";
@Shakespeared agreed it's not the most useful name. managedApp.kind() is an azure api to get the value of the 'kind' property and will return either 'ServiceCatalog' or 'Marketplace' depending on where the managed app was deployed from. I'll rename the config option to help clarify that we are actually looking at a type of managed app, but we are stuck with the Azure kind() call

2024-05-28 15:51 UTC, Shakespeared commented on src/main/resources/sam.conf
> +  kindServiceCatalog = "ServiceCatalog";
Thanks for clarifying, that makes sense!

2024-05-28 15:51 UTC, Shakespeared approved these changes

2024-05-28 16:20 UTC, merged