fixed list groups when email missing
broadinstitute/sam pull request #146
Opened 2018-05-01 11:09 UTC by dvoet

\<your comments for this PR go here\>

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

2018-05-01 16:23 UTC, gpolumbo-broad requested changes

2018-05-01 16:23 UTC, gpolumbo-broad commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/service/ManagedGroupService.scala
> +      // This will silently ignore any group where the email could not be loaded. This can happen when a
Are we sure we want to "silently ignore"?  Perhaps we should add just a simple log statement to let somebody know that the data is a little fouled up.

2018-05-03 13:21 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/service/ManagedGroupService.scala
> +      // This will silently ignore any group where the email could not be loaded. This can happen when a
I don't think this is a big deal nor do I think anything can really be done about it. I think the right thing to do is pretend that it does not exist.

2018-05-03 15:41 UTC, gpolumbo-broad approved these changes

2018-05-03 17:22 UTC, gpolumbo-broad commented
jenkins retest

2018-05-03 18:29 UTC, merged