Resource validation refactor
broadinstitute/sam pull request #147
Opened 2018-05-03 14:53 UTC by gpolumbo-broad

The goal of this refactor was:

- Get validations happening first, before anything is persisted
- Collect all the validation errors at once into a single `ErrorReport` so that all problems are reported to the requestor at once.
- Make the code eas(y)(ier) to add new validations to
- Reduce or eliminate need to execute some pieces of logic more than once

I'm not thrilled with the `PotentialAccessPolicy`.  The most important thing that it gave us is a place to wrap up the `Map[WorkbenchEmail, Option[WorkbenchSubject]]`, but it is also a package for bundling up into a single object the things we need to create a new `AccessPolicy`.   Anyway, it seems to help for now, so let me know what you think

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

2018-05-07 19:34 UTC, dvoet requested changes
see comments

2018-05-07 19:34 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/service/ResourceService.scala
> +    Future.sequence(eventualPolicyCreators.toSet)
Future.traverse instead of map followed by Future.sequence

2018-05-07 19:34 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/service/ResourceService.scala
> +    if (possibleErrors.nonEmpty) Some(possibleErrors) else None
general best practice is to never directly create an instance of Some. User Option(possibleErrors) instead of Some(possibleErrors). This protects against accidental Some(null) situations.

2018-05-07 19:34 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/model/SamModel.scala
> +case class PotentialAccessPolicy(policyName: AccessPolicyName, emailsToSubjects: Map[WorkbenchEmail, Option[WorkbenchSubject]], roles: Set[ResourceRoleName], actions: Set[ResourceAction])
this seems like something that should be private and internal to ResourceService

2018-05-07 19:34 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/service/ResourceService.scala
> +  private def validateCreateResource(resourceType: ResourceType, resourceId: ResourceId, policies: Set[PotentialAccessPolicy], userInfo: UserInfo): Option[Seq[ErrorReport]] = {
could this return just a Seq instead of Option[Seq]? Note that `case Seq()` matches an empty seq.

2018-05-07 19:34 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/service/ResourceService.scala
> +  private def makeCreatablePolicies(policies: Map[AccessPolicyName, AccessPolicyMembership]): Future[Set[PotentialAccessPolicy]] = {
pick a single term.. is it creatable or potential? how about validatable?

2018-05-09 14:53 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/service/ResourceService.scala
> +  case class PotentialAccessPolicy(policyName: AccessPolicyName, emailsToSubjects: Map[WorkbenchEmail, Option[WorkbenchSubject]], roles: Set[ResourceRoleName], actions: Set[ResourceAction])
If you feel strongly about the term Potential, fine, but it doesn't really speak to me. Why would a potential policy be different that the real one? I think I prefer Validatable.

2018-05-09 16:25 UTC, MatthewBemis approved these changes

2018-05-10 15:20 UTC, merged

2018-05-10 15:20 UTC, gpolumbo-broad commented
@dvoet gave thumb in slack