GAWB-3569 Can create specify Auth Domains on Resource creation
broadinstitute/sam pull request #159
Opened 2018-05-22 18:47 UTC by gpolumbo-broad

\<your comments for this PR go here\>

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

2018-05-23 13:11 UTC, gpolumbo-broad commented
jenkins retest

2018-05-23 14:26 UTC, dvoet requested changes
see comments

2018-05-23 14:26 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/service/ResourceService.scala
> +      directoryDAO.loadGroup(groupName) map {
this should check against managed groups... I think we should add a "use" action to managed groups that both members and admins have. Then this should check that the user has that action. If the user does not have that action then the error message should say that either the group does not exist or the user does not have access.

2018-05-23 14:51 UTC, MatthewBemis commented on src/main/resources/swagger/api-docs.yaml
> +      authDomains:
for here and elsewhere in the PR: authDomains should be singular. there's only ever 1 auth domain for a resource, which may be comprised of any number of managed groups

2018-05-23 18:33 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/service/ResourceService.scala
> +  private def validateAuthDomainPermissions(authDomain: Set[WorkbenchGroupName], userInfo: UserInfo): Future[Set[Option[ErrorReport]]] = Future.sequence(
User Future.traverse instead of sequence and map

2018-05-23 18:44 UTC, dvoet approved these changes

2018-05-24 14:06 UTC, MatthewBemis approved these changes

2018-05-24 14:24 UTC, merged