terminate actor system on failed init
broadinstitute/sam pull request #174
Opened 2018-06-15 19:59 UTC by MatthewBemis

\<your comments for this PR go here\>

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

2018-06-15 20:02 UTC, dvoet approved these changes

2018-06-15 20:03 UTC, gpolumbo-broad requested changes

2018-06-15 20:03 UTC, gpolumbo-broad commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/Boot.scala
>            logger.error("FATAL - could not update schema to latest version. Is the schema lock stuck? See documentation here for more information: [link]")
Missing the link

2018-06-15 20:08 UTC, gpolumbo-broad approved these changes

2018-06-26 20:04 UTC, MatthewBemis commented
note to self: update this to also terminate actor system if line 55 (initialize ldapConnectionPool) fails

2018-10-23 20:30 UTC, Qi77Qi commented
closing this per discussion https://broadinstitute.slack.com/archives/C9ZSW4R7U/p1540319446000100

2018-10-23 20:30 UTC, closed without merging