Update pr template
broadinstitute/sam pull request #191
Opened 2018-08-16 19:43 UTC by Qi77Qi

https://broadinstitute.atlassian.net/browse/GAWB-3744
Feedback is welcome!

Have you read [CONTRIBUTING.md](../CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

In all cases:

- [ ] Get two thumbsworth of review and PO signoff if necessary
- [ ] Verify all tests go green
- [ ] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [ ] Test this change deployed correctly and works on dev environment after deployment

2018-08-17 14:58 UTC, marctalbott approved these changes
I think it looks nice and simple. One possible thing to add would be a link to the section of the readme that holds the old template. This could keep the information easily accessible when opening PRs without sacrificing the simplicity of the new template.

2018-08-20 17:20 UTC, gpolumbo-broad requested changes

2018-08-20 17:20 UTC, gpolumbo-broad commented on .github/PULL_REQUEST_TEMPLATE.md
> +Notes:
If there's nothing left in this file we should just delete it.

If we still want a checklist, it could be something about who the required reviewers are, and if we want this, it is something we could automate with PullApprove.

2018-08-20 17:21 UTC, gpolumbo-broad commented
I don't think this should be merged until @dvoet has a chance to review it

2018-08-28 18:08 UTC, Qi77Qi commented
test

2018-08-31 19:45 UTC, dvoet approved these changes

2018-09-01 13:44 UTC, merged