GET /api/user/v1/{email}: Return user email, subject id, and google subject id
broadinstitute/sam pull request #214
Opened 2018-09-24 19:45 UTC by MatthewBemis

Ticket: <Link to Jira ticket>
<Put notes here to help reviewer understand this PR>

---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

2018-09-24 19:51 UTC, dvoet requested changes

2018-09-24 19:51 UTC, dvoet commented on src/main/resources/swagger/api-docs.yaml
> +  /api/user/v1/{email}:
I think this should be in the same top level URI as `/api/v1/invite/user/{inviteeEmail}` below (which is a little wrong anyway)

how about
`/api/users/v1/invite/{inviteeEmail}`
`/api/users/v1/info/{email}`

2018-09-24 20:20 UTC, Qi77Qi commented on src/test/scala/org/broadinstitute/dsde/workbench/sam/api/UserRoutesV1Spec.scala
> +    val googleSubjectIdHeader = TestSupport.googleSubjectIdHeaderWithId(user.googleSubjectId.get)
seems `googleSubjectIdHeader` is not used?

2018-09-24 20:20 UTC, Qi77Qi commented on src/test/scala/org/broadinstitute/dsde/workbench/sam/api/UserRoutesV1Spec.scala
> +  }
shall we add a negative test case too?

2018-09-24 20:28 UTC, Qi77Qi approved these changes

2018-09-25 18:01 UTC, dvoet approved these changes

2018-10-04 15:12 UTC, merged