Sam Phase II: List user's role on resource
broadinstitute/sam pull request #22
Opened 2017-09-25 14:57 UTC by MatthewBemis

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Make sure Swagger is updated if API changes
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via Slack and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2017-09-26 13:58 UTC, dvoet commented
a note on tests - Our service level function signatures are a lot more sane using akka http. So I am thinking that we should have functional level unit tests at the service layer, not the api layer. We should still have api tests but they should concern themselves with ensuring the api exists, has correct return codes and has output in the correct structure (i.e.  json for the right case class).

Thoughts?

2017-09-26 15:21 UTC, MatthewBemis commented
@dvoet i agree with that, i had gotten into the bad habit of not testing both. will update...

2017-09-27 03:21 UTC, dvoet approved these changes

2017-09-27 19:47 UTC, breilly2 requested changes
Only minor changes, but I think they're worth making.

2017-09-27 19:47 UTC, breilly2 commented on src/test/scala/org/broadinstitute/dsde/workbench/sam/api/ResourceRoutesSpec.scala
> +  it should "200 and return an empty list on list resource roles" in {
This test is identical to the `Get` part of `it should "200 on list resource roles" in`. Should either do something more interesting or one of the two should be removed.

2017-09-27 19:47 UTC, breilly2 commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/service/ResourceService.scala
> +  private def listResourceAccessPoliciesForUser(resourceType: ResourceType, resourceName: ResourceName, userInfo: UserInfo): Future[Set[AccessPolicy]] = {
This only needs `name` from `resourceType` so I propose that it take a `ResourceTypeName` instead of a full `ResourceType`.

2017-09-27 19:47 UTC, breilly2 commented on src/test/scala/org/broadinstitute/dsde/workbench/sam/service/ResourceServiceSpec.scala
> +    val resourceType = ResourceType(ResourceTypeName(UUID.randomUUID().toString), Set(ResourceAction("a1"), ResourceAction("a2"), ResourceAction("a3")), Set(ResourceRole(ownerRoleName, Set(ResourceAc
Are the `ResourceAction`s important to this test case? I don't see them being referenced other than when creating the resource type here.

2017-09-27 19:47 UTC, breilly2 commented on src/test/scala/org/broadinstitute/dsde/workbench/sam/service/ResourceServiceSpec.scala
> +  it should "listUserResourceRoles when the resource doesn't exist" in {
`it should "return an empty set from listUserResourceRoles when the resource doesn't exist"`

2017-09-28 14:01 UTC, MatthewBemis commented
@breilly2 back to you

2017-09-28 14:49 UTC, breilly2 approved these changes
👍

2017-09-28 18:47 UTC, merged