Automation test for checking that google groups are being synced appropriately
broadinstitute/sam pull request #228
Opened 2018-10-12 19:57 UTC by marctalbott

Ticket: [GAWB-3853](https://broadinstitute.atlassian.net/browse/GAWB-3853)
- a test that makes sure that group sync is actually updating the google group correctly

---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

2018-10-16 14:27 UTC, dvoet requested changes

2018-10-16 14:27 UTC, dvoet commented on automation/src/test/scala/org/broadinstitute/dsde/test/api/SamApiSpec.scala
> +      val managedGroupId = "fooGroup"
make this a random name, e.g. a random uuid with a prefix. Using a fixed name like this means concurrent test runs will interfere with each other or a failed cleanup in one test run will cause failure in the next.

2018-10-16 14:27 UTC, dvoet commented on automation/src/test/scala/org/broadinstitute/dsde/test/api/SamApiSpec.scala
> +        policy <- policies.asInstanceOf[Set[Map[String, Map[String, List[String]]]]] if policy.getOrElse("policy", Map.empty).getOrElse("memberEmails", List.empty).nonEmpty
I don't understand how this casting is working... seems fishy. Why doesn't listResourcePolicies return a structured result?

2018-10-16 14:27 UTC, dvoet commented on automation/src/test/scala/org/broadinstitute/dsde/test/api/SamApiSpec.scala
> +      TestKit.awaitCond(
I found a better way than awaitCond which is awaitAssert (which is in TestKitBase which your test class needs to extend). Inside awaitAssert call your normal asserts.

2018-10-16 17:33 UTC, Qi77Qi commented on automation/src/test/scala/org/broadinstitute/dsde/test/api/SamApiSpec.scala
> +      val managedGroupId = "fooGroup"
it's probably worth creating a scalacheck generator for this (similar to https://github.com/broadinstitute/sam/blob/develop/src/test/scala/Generator.scala#L77)

2018-10-18 19:31 UTC, Qi77Qi commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleExtensions.scala
> +          case basicGroupName: WorkbenchGroupName => directoryDAO.loadGroup(basicGroupName)
think you need to `unsafeToRunSync()` or `.futureValue` on these `loadGroup`?

2018-10-18 19:34 UTC, Qi77Qi commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleExtensions.scala
> +        group2 = groupOption2.getOrElse(throw new WorkbenchExceptionWithErrorReport(ErrorReport(StatusCodes.NotFound, s"$groupId not found")))
you can do `group2 <- IO.fromEither(groupOption2.toRight(throw new WorkbenchExceptionWithErrorReport(ErrorReport(StatusCodes.NotFound, s"$groupId not found")))).unsafeToFuture` (probably will be easier to move things to IO later this way too)

2018-10-23 20:13 UTC, dvoet approved these changes

2018-10-23 20:47 UTC, gpolumbo-broad approved these changes

2018-10-23 20:49 UTC, merged