create proxy groups for invites
broadinstitute/sam pull request #273
Opened 2019-01-16 19:01 UTC by dvoet

Ticket: https://broadinstitute.atlassian.net/browse/GAWB-4056
The gist is that a proxy group is not created when an invite is created. The intention was to create it when the user comes to the site. But this then requires a bunch of special case logic:
* exclude invites from google group sync (which we neglected)
* trigger group sync when an invite registers
* be careful in the ordering of proxy group creation and group syncing

It just seems easier, (less code and less cognitive load) to always create a proxy group.

We also need to back populate all existing invitations.

---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

2019-01-16 19:12 UTC, gpolumbo-broad requested changes

2019-01-16 19:12 UTC, gpolumbo-broad commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/service/UserService.scala
> +  def validateEmailAddress(email: WorkbenchEmail) = {
Tests for this?

2019-01-16 19:12 UTC, gpolumbo-broad commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/service/UserService.scala
> +    email.value match {
If the user entered some leading/trailing whitespace, can we just lop that off for them rather than throwing an error?

2019-01-16 19:12 UTC, Qi77Qi approved these changes

2019-01-16 19:12 UTC, Qi77Qi commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/service/UserService.scala
> +      case _ => IO.raiseError(new WorkbenchExceptionWithErrorReport(ErrorReport(StatusCodes.BadRequest, "invalid email address")))
shall we put the actual email address in the message as well just for debugging purpose?

2019-01-17 19:54 UTC, gpolumbo-broad approved these changes

2019-01-17 20:44 UTC, merged