flat map getAttributes
broadinstitute/sam pull request #317
Opened 2019-07-21 21:58 UTC by ansingh7115

Ticket: <Link to Jira ticket>
<Put notes here to help reviewer understand this PR>

---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

2019-07-21 22:09 UTC, dvoet approved these changes

2019-07-22 14:21 UTC, gpolumbo-broad requested changes

2019-07-22 14:21 UTC, gpolumbo-broad commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/util/LdapSupport.scala
> +     attributes.getValue
Perhaps a nit, but the naming choice to use plurals for `searchResultEntries` and `attributes` made me need to think twice and then confused me with the method below for a second.  I would prefer using variable names that are singular in this method.

2019-07-22 16:38 UTC, ansingh7115 commented
jenkins retest

2019-07-22 17:42 UTC, gpolumbo-broad approved these changes

2019-07-22 20:46 UTC, merged