Implemented `listUsersGroups` and test
broadinstitute/sam pull request #321
Opened 2019-07-24 19:20 UTC by gpolumbo-broad

Ticket: <Link to Jira ticket>
<Put notes here to help reviewer understand this PR>

---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

2019-07-24 20:10 UTC, marctalbott approved these changes

2019-07-25 00:18 UTC, dvoet requested changes

2019-07-25 00:18 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/directory/PostgresDirectoryDAO.scala
> +          ) select distinct(${g.name})
unfortunately WorkbenchGroupIdentity is not only WorkbenchGroups but also policies... you need to include possible policies in the result set

2019-07-29 14:56 UTC, dvoet approved these changes

2019-07-29 17:58 UTC, merged