Create resource type
broadinstitute/sam pull request #336
Opened 2019-08-02 21:26 UTC by gpolumbo-broad

Ticket: <Link to Jira ticket>
<Put notes here to help reviewer understand this PR>

---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

2019-08-02 21:30 UTC, gpolumbo-broad commented
@dvoet - This works, that was objective #1.  However, take a look at:

https://github.com/broadinstitute/sam/pull/336/files#diff-fa47ac5a3ac54133b082c1abbdaad58eR57

I don't think there's a way to do the `INSERT INTO SAM_ROLE_ACTION` with one query or without N*2 subqueries.  So you'll see I have it querying the database to get all the `ID`s for the Roles and Actions.  Not sure if you can think of a fancier way to do it.

2019-08-09 17:05 UTC, dvoet requested changes

2019-08-09 17:05 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/openam/PostgresAccessPolicyDAO.scala
> +    validateRoleActions(resourceType)
I don't think validation belongs here. We currently don't do it at all so this would be a behavior change. If we want to add it we should put it at the service level.

2019-08-09 17:05 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/openam/PostgresAccessPolicyDAO.scala
> +    validateRoleActions(resourceType)
also be careful with stuff like this as it executes outside the IO... the right way would be to make validateRoleActions return an IO then flatmap with the runInTransaction call.

2019-08-09 17:05 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/openam/PostgresAccessPolicyDAO.scala
> +  // you.  It is up to the caller to make sure the actions being saved are valid.
remove this comment, it refers to a higher level construct that may or may not apply

2019-08-09 17:05 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/openam/PostgresAccessPolicyDAO.scala
> +  // consequences to how we enforce auth domains.
yes to the question, make the comment scaladoc, not plain comment

2019-08-09 17:05 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/openam/PostgresAccessPolicyDAO.scala
> +    if (roleActionValues.nonEmpty) {
The filter on line 65 seems to do the same thing as this if condition. One or the other will do but don't need both. I prefer to have it here.

2019-08-09 17:05 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/openam/PostgresAccessPolicyDAO.scala
> +               from ${ResourceActionTable.table}
use a `ResourceActionTable.syntax` instead of `.table` and `.column`:
```val rat = ResourceActionTable.syntax("rat")```
then don't do `select *`, do `select ${rat.result.*}`

applies to other selects below. The rule is that `.table` and `.column` are used in inserts, updates and deletes and `.syntax` used in selects

2019-08-13 15:24 UTC, dvoet approved these changes

2019-08-14 15:39 UTC, merged