CA-554 Strings in postgres preserve case
broadinstitute/sam pull request #370
Opened 2019-10-18 19:59 UTC by gpolumbo-broad

Ticket: <Link to Jira ticket>
<Put notes here to help reviewer understand this PR>

---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've updated the RC_XXX release ticket with any manual steps required to release this change
- [ ] I've updated the [FISMA documentation](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#fisma-documentation-changes) if I've made any security-related changes, including auth, encryption, or auditing

2019-10-21 13:49 UTC, marctalbott reviewed
Is there a way to do this as a separate changeset? Not sure if you can modify a data type using a Liquibase changeset

2019-10-21 20:05 UTC, marctalbott approved these changes

2019-10-23 17:10 UTC, dvoet requested changes

2019-10-23 17:10 UTC, dvoet commented on src/main/resources/org/broadinstitute/dsde/sam/liquibase/changesets/20191021_citext_support.xml
> +    <changeSet id="alter_SAM_USER_id_to_citext" author="gpolumbo">
do we need to do this one?

2019-10-23 17:10 UTC, dvoet commented on src/main/resources/org/broadinstitute/dsde/sam/liquibase/changesets/20191021_citext_support.xml
> +    <changeSet id="alter_SAM_PET_SERVICE_ACCOUNT_project_to_citext" author="gpolumbo">
google project can only be lower case anyway

2019-10-23 17:12 UTC, dvoet commented
I do think tests would be nice but can follow in another PR if needed

2019-10-25 19:19 UTC, merged