[CA-1143] Sr bouncy castle
broadinstitute/sam pull request #524
Opened 2021-06-16 21:08 UTC by s-rubenstein

Ticket: <Link to Jira ticket>
<Put notes here to help reviewer understand this PR>

---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've filled out the [Security Risk Assessment](https://broadinstitute.github.io/dsp-appsec-security-risk-assessment/) and attached the result to the JIRA ticket

2021-06-16 21:11 UTC, andy7i approved these changes

2021-06-16 21:36 UTC, MatthewBemis approved these changes

2021-06-17 13:14 UTC, gpolumbo-broad requested changes
I'm wondering if just _adding_ the dependency to Sam is the right solution here?  If the problem is in Workbench Libs, then it seems to me that the solution should exist in Workbench Libs.  I wonder if appsec found this error in all of their scans of all services that use Workbench Libs?  Anyway, I think that is the better place to implement the fix.

2021-06-17 13:43 UTC, s-rubenstein commented
@gpolumbo-broad ah! I didn't realize it was a workbench libs problem. The ticket seemed to make it seem like it was just a Sam and Rawls issue. I can look into that, but I have no clue how to verify that it solves the problem. Is the right process for that to ping AppSec after making the change, and have them tell us?

2021-06-22 15:19 UTC, closed without merging