[QA-1240] Only sync constrained policies that have been synced before
broadinstitute/sam pull request #551
Opened 2021-10-29 19:15 UTC by marctalbott

Ticket: [QA-1240](https://broadworkbench.atlassian.net/browse/QA-1240)
When we update an auth domain group, we add all of the policies constrained by that auth domain to the group synchronizer queue. The group synchronizer doesn't check whether a group has been synced in the past because it is responsible for first time syncs and just blindly syncs any group it gets off the queue. This can lead to a timing issue that interferes with workspace deletion in tests with constrained resources.

1. Constrained workspace is created with all 8 of its policies and Rawls tells Sam to sync 5 of those policies immediately (`project-owner`, `owner`, `writer`, `reader`, `can-compute`). The logs indicate that the Google call to create the Google groups for these policies (aka syncing them) occurs <1 second after the workspace is created.
2. Auth domain group is modified later. This adds the auth domain group to the group sync queue along with all of the policies it constrains. This includes all of the workspace policies, not just the 5 that have been synced before.
3. The synchronizer eventually gets around to syncing the messages generated above. For the 3 previously unsynced policy groups (`can-catalog`, `share-reader`, `share-writer`), the synchronizer creates new Google groups.
4. While this is going on in the background, the test completes and begins cleaning up the workspace. This logic in Sam tries to delete all Google groups for all policies on the resource, whether those policies have been synced or not.
5. The requests to delete the policy groups are issued right around the same time as the requests to create the previously unsynced policy groups. These requests conflict with each other, and Google rightfully returns a 409. This failure prevents Sam from deleting the policies in Postgres.
6. The workspace isn't deleted correctly in Sam, so the billing-project can't be deleted since the billing-project owner policy is a member of the workspace project-owner policy.

This PR makes it so we only sync policies that have been synced previously by checking for a last synchronized date before adding the policy to the group sync queue. If a constrained policy hasn't been synced in the past, then there's no point in syncing it when the auth domain group gets synced since nobody is using the unsynced policy to grant access to cloud resources.

---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've filled out the [Security Risk Assessment](https://broadinstitute.github.io/dsp-appsec-security-risk-assessment/) and attached the result to the JIRA ticket

2021-10-29 19:45 UTC, ehigham approved these changes

2021-11-01 14:31 UTC, gpolumbo-broad requested changes

2021-11-01 14:31 UTC, gpolumbo-broad commented on src/test/scala/org/broadinstitute/dsde/workbench/sam/dataAccess/MockAccessPolicyDAO.scala
> +  override def listSyncedAccessPolicyIdsOnResourcesConstrainedByGroup(groupId: WorkbenchGroupIdentity, samRequestContext: SamRequestContext): IO[Set[FullyQualifiedPolicyId]] = ???
Looks like this is never used directly and is always mocked, which is fine, but leaving the `???` here forced me to go do that check.  I'm fine leaving the `???`, but a comment might be a good idea to briefly explain why this was done.  Or maybe just have it return an empty `Set`.

2021-11-01 14:40 UTC, gpolumbo-broad commented
FWIW - talked faces with @marctalbott on this to clarify some things.  A few key takeaways:

- We want the synchronizer to remain sort of naive, it syncs whatever its told to sync
- The logic for whether something should be sync'd or not should happen when trying to determine what should or should not be put onto the synchronizer queue
- We believe that the `can-catalog`, `share-reader`, and `share-writer` polices should not be getting sync'd and the fact that they _are_ being sync'd today is a bug.  This PR fixes that bug
- _IF_ there is logic in production code or tests that counts on those policies being sync'd, this PR _will_ break that code and whatever that code is, it should be fixed or it can directly call the Sam `sync` endpoint to explicitly request that the policy be sync'd, which is perfectly valid.  (Explicitly requesting a policy to be sync'd is fine.  Sam auto-magically sync'ing policies that were _never_ explicitly requested to be sync'd is the bug)
- In theory, we _could_ write an integration test in Rawls or something that creates an auth domain constrained resource, updates the auth domain, and then checks that Google still only knows about exact policies it asked Sam to sync.  There should be no "bonus" policies for that resource that showed up in Google as sync'd.  We are not going to write that test now though.

2021-11-02 15:40 UTC, gpolumbo-broad approved these changes

2021-11-02 17:25 UTC, merged

2021-11-02 18:48 UTC, araina2018 commented
Thanks @marctalbott @gpolumbo-broad  for detailed takeaways. Noting the last bullet which is beyond the current unblocking monolith scope but a key takeaway - Sam/ Rawls/Orch test suites review to ensure we test the integration of these components adequately without conflating / confusing the purpose of each test in these test suites.