GAWB-3018: Store and retrieve pet SA keys
broadinstitute/sam pull request #82
Opened 2018-01-12 20:48 UTC by MatthewBemis

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Make sure Swagger is updated if API changes
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via Slack and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2018-01-12 20:50 UTC, MatthewBemis commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleExtensionRoutes.scala
> +                  googleKeyCache.getKey(WorkbenchUser(userInfo.userId, userInfo.userEmail), GoogleProject(project)).map(key => StatusCodes.OK -> key.parseJson)
some of these changes duplicate effort in #81 

i'll rectify once that goes into dev

2018-01-17 14:24 UTC, MatthewBemis commented on project/Dependencies.scala
> +  val workbenchGoogleV = "0.10-7e24549-SNAP"
note to self: swap out for finalized version

2018-01-17 16:46 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleKeyCache.scala
> +    googleStorageDAO.createBucket(googleServicesConfig.serviceAccountClientProject, petServiceAccountConfig.keyBucketName).map { _ =>
flatMap? what happens if the bucket already exists?

2018-01-17 16:46 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleKeyCache.scala
> +    } yield key.privateKeyData.decode.getOrElse(throw new WorkbenchException(s"could not decode service account private key data for key ${key.id}"))
only decode once and this exception will never happen on this line because an exception would be thrown first on the line above

2018-01-17 16:46 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/Boot.scala
> +        val googleKeyCache = new GoogleKeyCache(directoryDAO, googleIamDAO, googleStorageDAO, googleExtensions, googleServicesConfig, petServiceAccountConfig)
I think google key cache should be internal to google extensions.

2018-01-17 16:46 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/service/KeyCache.scala
> +  def getKey(user: WorkbenchUser, project: GoogleProject): Future[String]
what if the parameter here is the PetServiceAccount? It has all the information and then the cache code can rely on the fact that the pet already exists.

2018-01-17 16:46 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleExtensionRoutes.scala
> +                googleKeyCache.getKey(WorkbenchEmail(userEmail), GoogleProject(project)) map {
if GoogleKeyCache is internal to google extension, this file need not change

2018-01-17 16:46 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleKeyCache.scala
> +  def getKey(userEmail: WorkbenchEmail, project: GoogleProject): Future[Option[String]] = {
if we need this function it should be in the trait

2018-01-17 21:08 UTC, MatthewBemis commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleKeyCache.scala
> +      case (Nil, _) => furnishNewKey(pet, project) //mismatch. there were no keys found in the bucket, but there may be keys on the service account
there's a change i can make to the GoogleIamDAO that will make this case much less likely. it currently returns all system managed keys and user managed keys, but we can filter out the user managed keys

2018-01-18 18:17 UTC, MatthewBemis commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleKeyCache.scala
> +    googleStorageDAO.createBucket(googleServicesConfig.serviceAccountClientProject, petServiceAccountConfig.keyBucketName).map { _ =>
if the bucket already exists the operation still succeeds. GoogleStorageDAO handles this case.

2018-01-19 19:18 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleExtensions.scala
> +      key <- googleKeyCache.getKey(pet, project)
project is included in the PetServiceAccount object, no need to pass it in here too

2018-01-19 19:24 UTC, dvoet commented on src/test/resources/reference.conf
> +  retiredKeyMaxAge = 14
make these values 12 days for active and 60 for retired

2018-01-19 19:25 UTC, dvoet approved these changes
a couple minor tweaks then 👍

2018-01-22 14:04 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleKeyCache.scala
> +    googleStorageDAO.createBucket(googleServicesConfig.serviceAccountClientProject, petServiceAccountConfig.keyBucketName).flatMap { _ =>
what if this bucket already exists?

2018-01-22 20:18 UTC, breilly2 requested changes
Other than a couple of small things, the code looks good. Would like to see tests.

2018-01-22 20:18 UTC, breilly2 commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/config/PetServiceAccountConfig.scala
> +case class PetServiceAccountConfig(googleProject: GoogleProject, serviceAccountUsers: Set[WorkbenchEmail], keyBucketName: String, activeKeyMaxAge: Int, retiredKeyMaxAge: Int)
Please document units for `activeKeyMaxAge` and `retiredKeyMaxAge`.

2018-01-22 20:18 UTC, breilly2 commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleKeyCache.scala
> +    val mostRecentKeyName = keyObjects.sortBy(_.getTimeCreated.getValue).last.getName //here is where we'll soon ask the question: "is this key still active?" if it's not, we'll create a new key
How soon is "soon"?

2018-01-22 20:18 UTC, breilly2 commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleKeyCache.scala
> +  private def retrieveActiveKey(pet: PetServiceAccount, keyObjects: List[StorageObject], keys: List[ServiceAccountKey]): Future[String] = {
`keys` is unused. Is it going to be needed "soon"?

2018-01-22 20:18 UTC, breilly2 commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleKeyCache.scala
> +      _ <- googleStorageDAO.removeObject(petServiceAccountConfig.keyBucketName, keyNameFull(pet.id.project, pet.serviceAccount.email, keyId))
Should remove it from the bucket first to prevent it from being handed out while being removed (in the case that it's still active and the most recent).

2018-01-22 20:18 UTC, breilly2 commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleKeyCache.scala
> +      keys <- googleIamDAO.listServiceAccountKeys(pet.id.project, pet.serviceAccount.email, true)
Nit: More for the workbench-libs PR but I prefer separate functions over one function that takes a boolean, e.g. something like `listAllServiceAccountKeys` and `listUserManagedServiceAccountKeys`, because it's easier to understand than having to remember what a boolean means.

2018-01-22 20:18 UTC, breilly2 commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/service/KeyCache.scala
> +object NoKeyCache extends NoKeyCache
I don't see any usage. Can this be removed?

2018-01-22 20:18 UTC, breilly2 commented on src/test/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleExtensionRoutesSpec.scala
> +    (googleStorageDAO, expectedJson)
This function is only called in one place and that place ignores `expectedJson`.

2018-01-23 14:24 UTC, MatthewBemis commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/google/GoogleKeyCache.scala
> +    val mostRecentKeyName = keyObjects.sortBy(_.getTimeCreated.getValue).last.getName //here is where we'll soon ask the question: "is this key still active?" if it's not, we'll create a new key
"soon" is in my next PR, so by the end of the week

2018-01-23 14:25 UTC, MatthewBemis commented on src/main/scala/org/broadinstitute/dsde/workbench/sam/service/KeyCache.scala
> +object NoKeyCache extends NoKeyCache
yeah, it was used earlier in development but now it's not needed

2018-01-24 14:52 UTC, MatthewBemis commented
jenkins retest

2018-01-24 16:08 UTC, MatthewBemis commented
jenkins retest

2018-01-24 18:54 UTC, breilly2 approved these changes
👍

2018-01-24 19:18 UTC, MatthewBemis commented
jenkins retest

2018-01-24 20:34 UTC, merged