ID-363 let Sam host privacy policy in tandem with ToS
broadinstitute/sam pull request #920
Opened 2022-12-02 18:46 UTC by tlangs

Ticket: https://broadworkbench.atlassian.net/browse/ID-363

  \<Don't forget to include the ticket number in the PR title!\>

What:

Makes Sam host the Terra Privacy Policy as well as the Terms of Service.

Why:

The Terms of Service and Privacy are updated at the same time, and users need to accept the new bundle of documents before continuing to use Terra. Having Sam host both the Terms of Service and Privacy Policy means both can be updated at once with a single config change, meaning we don't need to coordinate UI and Sam PRs. It also means the Privacy Policy version is configurable per-environment, which is really useful for keeping prod and pre-prod on different versions.

How:

Just like the Terms of Service, the Privacy Policy is now kept in Sam's resources folder, and versioned. Sam now has the ability to serve up the text of the Privacy Policy, and the text served is based on Sam's configured Terms of Service version.

---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've filled out the [Security Risk Assessment](https://broadinstitute.github.io/dsp-appsec-security-risk-assessment/) and attached the result to the JIRA ticket

2022-12-06 19:46 UTC, gpolumbo-broad requested changes
Should probably add some tests

2022-12-06 22:20 UTC, tlangs commented
@gpolumbo-broad added a test

2022-12-07 17:41 UTC, Ghost-in-a-Jar approved these changes

2022-12-07 18:33 UTC, gpolumbo-broad approved these changes

2022-12-07 18:48 UTC, merged