[IA-4012] give kubernetes-app resource workspace inheritance
broadinstitute/sam pull request #989
Opened 2023-02-14 21:15 UTC by LizBaldo

Ticket: https://broadworkbench.atlassian.net/browse/IA-4012

What:

Give app permission inheritance from Workspace in addition to the Google Project. This will enable a better user experience with V2 apps.

Why:

 This way the behavior of the `kubernetes-app` resource will be similar to the new `kubernetes-app-shared` resource. 
https://github.com/broadinstitute/sam/pull/965

We want to keep the inheritance from the Google project for now to avoid any breaking change or need for a migration quite yet on legacy apps.

How:

Creator and manager roles both inherit from the workspace owner, while the manager role also inherit from the workspace reader and writer roles.

---

**PR checklist**

- [ ] I've followed [the instructions](https://github.com/broadinstitute/sam/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes
- [ ] I've filled out the [Security Risk Assessment](https://sdarq.dsp-appsec.broadinstitute.org/jira-ticket-risk-assesment) (requires Broad Internal network access) and attached the result to the JIRA ticket

2023-02-14 21:54 UTC, rtitle commented on src/main/resources/reference.conf
> +          kubernetes-app = ["creator", "manager"]
I think we only want to give workspace owners `manager` role on kubernetes-app. Similar to `google-project`: https://github.com/broadinstitute/sam/blob/develop/src/main/resources/reference.conf#L608-L614

So here:
```
kubernetes-app = ["manager"]
```

2023-02-14 21:56 UTC, rtitle commented on src/main/resources/reference.conf
> +          kubernetes-app = ["manager"]
I don't think workspace writers or readers should inherit any permissions to `kubernetes-app`. Only workspace owners should be able to manage kubernetes-apps in the workspace.

So remove this line, and the below.

2023-02-14 21:56 UTC, rtitle commented on src/main/resources/reference.conf
> +          kubernetes-app = ["manager"]
Remove as well

2023-02-14 21:56 UTC, rtitle requested changes
See above -- I think this PR will end up being a 1-liner :)

2023-02-14 21:58 UTC, LizBaldo commented
Indeed, I had it backwards 😵‍💫 
How about now?

2023-02-14 21:59 UTC, rtitle approved these changes
:shipit: !

2023-02-15 17:22 UTC, jdcanas approved these changes

2023-02-21 18:45 UTC, merged